language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
cache: bundler
env:
  - DATABASE_URL=postgres://postgres@localhost/postgres
services:
  - postgresql
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
